name: Make a .deb package

on: 
  push:
    #branches: ## need this for testing, uncomment later.
    #  - master

jobs:
  pkg-deb:
    runs-on: ubuntu-latest
    name: Deb Package
    steps:
      - uses: actions/checkout@v4
      - name: Install devscripts
        run: |
          sudo apt update
          sudo apt install devscripts libcairo2-dev git gcc python3 python3-dev libgirepository1.0-dev libostree-dev fuse-overlayfs python3-venv libcap-dev autoconf python3-gi python3-tomli debhelper-compat
      - name: Run debian pkg script
        run: |
          git fetch --all
          bash pkg/debian/build-debian.sh
      - name: Upload new deb
        uses: actions/upload-artifact@v4
        with:
          path: "../maps*.deb"

