name: Make a .deb package

on: 
  push:
    branches:
      - master

jobs:
  pkg-deb:
    runs-on: ubuntu-latest
    name: Deb Package
    steps:
      - uses: actions/checkout@v3
      - name: Run debian pkg script
        run: |
          git fetch --all
          bash pkg/debian/build-debian.sh $(git tag --sort "-committerdate" | cut -d$'\n' -f1) $(git tag --sort "-committerdate" | cut -d$'\n' -f2)
