name: Make a .deb package

on: push

jobs:
  pkg-deb:
    runs-on: ubuntu-latest
    name: Deb Package
    steps:
      - uses: actions/checkout@v3
      - name: Check thingy
        run: echo "${{github.ref_name}}"
