name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          sudo apt-get install meson ostree libcairo2-dev gcc python3-dev libgirepository1.0-dev libostree-dev fuse-overlayfs libcap-dev autoconf
          python -m pip install -r requirements.txt
      - name: Run tests
        run: pytest -vv
